### PR TITLE
POSIXct fixes

### PR DESCRIPTION
**Pull request by kenahoo**
This PR adds some tests for converting to `POSIXct` objects with timezones, then makes small changes to the code to get them passing.

### CODE REVIEW

**Comment by kenahoo** [comment]
So the reason I started on this was that my code's datetimes weren't converting properly using `rpy2`, and I noticed that the tests didn't cover my case, so I added those cases to the tests and then fixed the code to get them passing.

I also noticed that `master` was failing a test for me even before I made any changes (see output below), so I also fixed `test_POSIXct_datetime_from_timestamp()` while I had the patient's chest open.

```
FAILED [ 89%]
rpy2/tests/robjects/test_vector_datetime.py:105 (test_POSIXct_datetime_from_timestamp)
def test_POSIXct_datetime_from_timestamp():
>       tzone = robjects.vectors.get_timezone()

tests/robjects/test_vector_datetime.py:107: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
robjects/vectors.py:854: in get_timezone
    timezone = tzlocal.get_localzone()
../../../.pyenv/versions/rpy2/lib/python3.10/site-packages/tzlocal/unix.py:203: in get_localzone
    _cache_tz = _get_localzone()
../../../.pyenv/versions/rpy2/lib/python3.10/site-packages/tzlocal/unix.py:185: in _get_localzone
    utils.assert_tz_offset(tz)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

tz = _PytzShimTimezone(zoneinfo.ZoneInfo(key='America/Chicago'), 'America/Chicago')

    def assert_tz_offset(tz):
        """Assert that system's timezone offset equals to the timezone offset found.
    
        If they don't match, we probably have a misconfiguration, for example, an
        incorrect timezone set in /etc/timezone file in systemd distributions."""
        tz_offset = get_tz_offset(tz)
        system_offset = get_system_offset()
        if tz_offset != system_offset:
            msg = (
                "Timezone offset does not match system offset: {} != {}. "
                "Please, check your config files."
            ).format(tz_offset, system_offset)
>           raise ValueError(msg)
E           ValueError: Timezone offset does not match system offset: -18000 != -21600. Please, check your config files.

../../../.pyenv/versions/rpy2/lib/python3.10/site-packages/tzlocal/utils.py:63: ValueError
```

**Comment by lgautier** [comment]
Thanks for the PR. The linter is tripping on a few things. I am happy to review after they are fixed.

**Comment by lgautier** [comment]
Thanks for the PR. I edited a bit the unit tests to use parametrization instead of loop. It ensures that all tests runs even if one set of parameters fails, and it reports for which parameters when tests fail.

The fix will be included in the next rpy2 release.

**Comment by lgautier** [comment]
Fixes issue #914.

**Pull request merged**
