### PR TITLE
Change rpy2py(v) by rpy2py_listvector(v) to handle columns with lists…

### PR DESCRIPTION
**Pull request by romainstuder**
I have found a problem when dealing with R DataFrames which contain a mixture of columns with characters/scalars and columns with lists.

The solution could be in the function `rpy2py_dataframe(obj)` in `pandas2ri.py`. Replacing `rpy2py(v)` by `rpy2py_listvector(v)` seems to solve the problem and allow more flexibility.

### CODE REVIEW

**Comment by romainstuder** [comment]
Hi! I just cannot convert the result of a function to a Pandas DataFrame. Here is a code that is not working with 3.3.5, but working fine with my patch.

```python
import pandas as pd  
import rpy2 
import rpy2.robjects as ro 
from rpy2.robjects import pandas2ri 
from rpy2.robjects.conversion import localconverter
```

**Convert between R DF and Pandas DF**

```python
def r2py_df(r_df: ro.DataFrame) -> pd.DataFrame:
    Preserves row and column names
    Args:
        r_df (R data.frame): R dataframe to convert
    Returns:
        pd_df (DataFrame): pd.DataFrame
    """
    with localconverter(ro.default_converter + pandas2ri.converter):
        py_recarray = ro.conversion.rpy2py(r_df)
    pd_df = pd.DataFrame(py_recarray)
    pd_df.index = list(pd_df.index)
    return pd_df
```

**Main R function:**

```python
fgseaRes = ro.r('''
library("fgsea")

genesets_with_names <- list()
genesets_with_names$group1 <- c('g1', 'g2', 'g5')
genesets_with_names$group2 <- c('g5', 'g6', 'g7')
genesets_with_names$group3 <- c('g1', 'g2', 'g3', 'g4', 'g5','g6', 'g7')
genesets_with_names$group4 <- c('g1')

correlations <- c("g1"=1.0, "g2"=1.0, "g3"=0.9, "g4"=0.5, "g5"=0.0, "g6"=-0.1, "g7"=0.1)

fgseaRes <- fgsea(pathways = genesets_with_names, 
                  stats    = correlations,
                  minSize  = 2,
                  maxSize  = 6,
                  nperm    = 200)
        ''')
```
`R[write to console]: Loading required package: Rcpp`

**Convert the R DataFrame fgseaRes to a Pandas DataFrame:**
```python
with localconverter(ro.default_converter + pandas2ri.converter):
    py_recarray = ro.conversion.rpy2py(fgseaRes)
df_fgseaRes = pd.DataFrame(py_recarray)
```

With current version 3.3.5:
```python
[...]
`~/.pyenv/versions/3.7.8/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py in rpy2py_dataframe(obj)
    253 def rpy2py_dataframe(obj):
    254     items = OrderedDict((k, rpy2py(v) if isinstance(v, Sexp) else v)
--> 255                         for k, v in obj.items())
    256     res = PandasDataFrame.from_dict(items)
    257     res.index = obj.rownames` 
[...] 
TypeError: 'NULLType' object is not iterable
```

With the patch (3.4.0.dev):
```python
df_fgseaRes
```

pathway | pval | padj | ES | NES | nMoreExtreme | size | leadingEdge
-- | -- | -- | -- | -- | -- | -- | --
group1 | 0.066667 | 0.126984 | 1.0 | 1.472144 | 9.0 | 3 | [g1, g2]
group2 | 0.126984 | 0.126984 | -1.0 | -1.893130 | 7.0 | 3 | [g6, g5, g7]

```python
df_fgseaRes['leadingEdge']
```

1        [g1, g2]
2    [g6, g5, g7]
Name: leadingEdge, dtype: object

```python
df_fgseaRes['leadingEdge']["2"]
```
array(['g6', 'g5', 'g7'], dtype='<U2')

**Comment by lgautier** [comment]
Thanks for the report and patch.

It solves the very error you have, but I am not sure that it is the general way to solve it. It might introduce more consistency issues to rpy2's conversion system. `rpy2py(v)` should already dispatch to `rpy2py_listvector()`.

Do you have the full backtrace ?

What are the class and type of the object ? (see below)

```python
with localconverter(ro.default_converter:
    print(robjects.globalenv['fgseaRes'].rclass)
    print(robjects.globalenv['fgseaRes'].typeof)
```

**Comment by romainstuder** [comment]
> It solves the very error you have, but I am not sure that it is the general way to solve it. It might introduce more consistency issues to rpy2's conversion system. `rpy2py(v)` should already dispatch to `rpy2py_listvector()`.

Yes, I understand your point, as the function has not been fully tested against every possible cases. An alternative would be to have a side function that works on that particular case. Is this doable?

> Do you have the full backtrace ?

No, I don't have it. What would you need in particular?

> What are the class and type of the object ? (see below)
> 
> ```python
> with localconverter(ro.default_converter:
>     print(robjects.globalenv['fgseaRes'].rclass)
>     print(robjects.globalenv['fgseaRes'].typeof)
> ```

robjects.globalenv['fgseaRes'].rclass =>
<rpy2.rinterface_lib.sexp.StrSexpVector object at 0x1244f2460> [RTYPES.STRSXP]

robjects.globalenv['fgseaRes'].typeof =>
RTYPES.VECSXP

**Comment by lgautier** [comment]
> > It solves the very error you have, but I am not sure that it is the general way to solve it. It might introduce more consistency issues to rpy2's conversion system. `rpy2py(v)` should already dispatch to `rpy2py_listvector()`.
> 
> Yes, I understand your point, as the function has not been fully tested against every possible cases. An alternative would be to have a side function that works on that particular case. Is this doable?

rpy2's behavior can be configured in a quite a few way. If there is no general solution, there should be a workaround.

> > Do you have the full backtrace ?
> 
> No, I don't have it. What would you need in particular?

The full backtrace might help me see what the root of problem is (without having to install Bioconductor + `fgsea`).

> > What are the class and type of the object ? (see below)
> > ```python
> > with localconverter(ro.default_converter:
> >     print(robjects.globalenv['fgseaRes'].rclass)
> >     print(robjects.globalenv['fgseaRes'].typeof)
> > ```
> 
> robjects.globalenv['fgseaRes'].rclass =>
> <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x1244f2460> [RTYPES.STRSXP]

Interesting. It is an rinterface-level object rather than an robject-level one. May be a buglet in rpy2's S4 wrappers.
Can you try instead:

```python
with localconverter(ro.default_converter:
    print(tuple(robjects.globalenv['fgseaRes'].rclass))
```

> robjects.globalenv['fgseaRes'].typeof =>
> RTYPES.VECSXP

So that's an R list for sure, but not necessarily a data frame. I'll need the R class (see above).

**Comment by romainstuder** [comment]
> > > It solves the very error you have, but I am not sure that it is the general way to solve it. It might introduce more consistency issues to rpy2's conversion system. `rpy2py(v)` should already dispatch to `rpy2py_listvector()`.
> > 
> > 
> > Yes, I understand your point, as the function has not been fully tested against every possible cases. An alternative would be to have a side function that works on that particular case. Is this doable?
> 
> rpy2's behavior can be configured in a quite a few way. If there is no general solution, there should be a workaround.
> 
> > > Do you have the full backtrace ?
> > 
> > 
> > No, I don't have it. What would you need in particular?
> 
> The full backtrace might help me see what the root of problem is (without having to install Bioconductor + `fgsea`).
> 
> > > What are the class and type of the object ? (see below)
> > > ```python
> > > with localconverter(ro.default_converter:
> > >     print(robjects.globalenv['fgseaRes'].rclass)
> > >     print(robjects.globalenv['fgseaRes'].typeof)
> > > ```
> > 
> > 
> > robjects.globalenv['fgseaRes'].rclass =>
> > <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x1244f2460> [RTYPES.STRSXP]
> 
> Interesting. It is an rinterface-level object rather than an robject-level one. May be a buglet in rpy2's S4 wrappers.
> Can you try instead:
> 
> ```python
> with localconverter(ro.default_converter:
>     print(tuple(robjects.globalenv['fgseaRes'].rclass))
> ```
> 
> > robjects.globalenv['fgseaRes'].typeof =>
> > RTYPES.VECSXP
> 
> So that's an R list for sure, but not necessarily a data frame. I'll need the R class (see above).



Hi! 

I kept this in my backlog, but I have more time to work on it now.

```with localconverter(ro.default_converter):
    print(tuple(ro.globalenv['fgseaRes'].rclass))```
=> `('data.table', 'data.frame')`

I tried to download the latest dev release, but it sill doesn't work for my  special case. I also noticed the function I used, `rpy2py_listvector()`, disappeared form the code, in a commit from 18th of April: https://github.com/rpy2/rpy2/commit/00f411f928a4d6d79fa52c07f74e084bd8f6afee#diff-ff5d975e8f9c5ea0884d5845694f3d877be4f707e005dbd29031eb7130f30091

What is the alternative to this function `rpy2py_listvector()`?

**Comment by romainstuder** [comment]
It seems the recent release (3.4.5) of Rpy2 can now handle dataframes with lists. I am using `pd_df = pd.DataFrame(r_df, index=r_df.names).T`, which seems to work. I am closing this PR.

**Pull request closed without merging**
